name: Build Android APK

on:
  push:
    branches:
      - features
  pull_request:
    branches:
      - features

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd native-app
          npm install
          npm install -g react-native-cli

      - name: Setup Java and Gradle
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Install dependencies with Gradle
        run: |
          cd native-app/android
          ./gradlew dependencies

      - name: Build APK
        run: |
          cd native-app/android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: native-app/android/app/build/outputs/apk/release/app-release.apk
